name: simple
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  geoflutterfire_plus:
    path: ../
  google_maps_flutter: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
