name: simple
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.5
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  geoflutterfire_plus:
    path: ../
  google_maps_flutter: ^2.2.5
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
