version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "KosukeSaigusa"
    reviewers:
      - "KosukeSaigusa"
  - package-ecosystem: "pub"
    directory: "/example"
    schedule:
      interval: "daily"
    assignees:
      - "KosukeSaigusa"
    reviewers:
      - "KosukeSaigusa"
