name: geoflutterfire_plus
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/KosukeSaigusa/getflutterfire_ks

environment:
  sdk: '>=2.18.0 <3.0.0'
  # flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^4.3.0
  rxdart: ^0.27.7
  # flutter:
  #   sdk: flutter

dev_dependencies:
  pedantic_mono: ^1.20.1
  # flutter_test:
  #   sdk: flutter
  # flutter_lints: ^2.0.0

# flutter:

