name: geoflutterfire_plus
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/KosukeSaigusa/getflutterfire_ks

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  cloud_firestore: ^4.3.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.20.1
