name: geoflutterfire_plus
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/KosukeSaigusa/getflutterfire_ks

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.0
  equatable: ^2.0.5
  rxdart: ^0.27.7

dev_dependencies:
  pedantic_mono: ^1.20.1
