name: geoflutterfire_plus
description: geoflutterfire_plus enable your flutter app to store and query cloud firestore documents based on their geographic location.
version: 0.0.2
homepage: https://github.com/KosukeSaigusa/getflutterfire_plus

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  cloud_firestore: ^4.4.3
  flutter:
    sdk: flutter
  rxdart: ^0.27.7

dev_dependencies:
  fake_cloud_firestore: ^2.4.0
  flutter_test:
    sdk: flutter
